-- MySQL Script generated by MySQL Workbench
-- Wed May 31 22:37:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cor` VARCHAR(45) NULL,
  `icone` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Categoria_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Categoria_user1_idx` ON `mydb`.`Categoria` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  `Categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Item_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `mydb`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Item_Categoria1_idx` ON `mydb`.`Item` (`Categoria_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ItemLista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ItemLista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ItemLista` (
  `id` INT NOT NULL,
  `checked` TINYINT NULL,
  `Lista_id` INT NOT NULL,
  `Item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ItemLista_Lista1`
    FOREIGN KEY (`Lista_id`)
    REFERENCES `mydb`.`Lista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemLista_Item1`
    FOREIGN KEY (`Item_id`)
    REFERENCES `mydb`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ItemLista_Lista1_idx` ON `mydb`.`ItemLista` (`Lista_id` ASC) VISIBLE;

CREATE INDEX `fk_ItemLista_Item1_idx` ON `mydb`.`ItemLista` (`Item_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Lista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lista` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `icone` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Lista_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Lista_user1_idx` ON `mydb`.`Lista` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`agendamentoItemLista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agendamentoItemLista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agendamentoItemLista` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `dt_inicio` VARCHAR(45) NULL,
  `dt_fim` VARCHAR(45) NULL,
  `dt_agendamento` VARCHAR(45) NULL,
  `nr_sequencia` VARCHAR(45) NULL,
  `frequencia` VARCHAR(45) NULL,
  `ItemLista_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_agendamentoItemLista_ItemLista1`
    FOREIGN KEY (`ItemLista_id`)
    REFERENCES `mydb`.`ItemLista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_agendamentoItemLista_ItemLista1_idx` ON `mydb`.`agendamentoItemLista` (`ItemLista_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
